# Generated by Django 3.2.3 on 2021-06-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopperProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30)),
                ('pro_desc', models.TextField(max_length=100)),
                ('pro_price', models.IntegerField()),
                ('pro_img', models.ImageField(upload_to='pics')),
                ('pro_ID', models.CharField(max_length=20)),
            ],
        ),
    ]
