# Generated by Django 3.2.3 on 2021-06-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_alter_shopperproduct_pro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperproduct',
            name='pro_img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
