# Generated by Django 3.2.3 on 2021-06-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_alter_shopperregistration_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopperregistration',
            name='user_img',
            field=models.ImageField(default='none', upload_to='userImg'),
        ),
    ]
