# Generated by Django 3.2.3 on 2021-06-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_shopperregistration_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopperregistration',
            name='u_password',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
