# Generated by Django 3.2.3 on 2021-07-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_shopperregistration_u_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperproduct',
            name='pro_ID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
