# Generated by Django 3.2.3 on 2021-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_alter_shopperproduct_pro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopperproduct',
            name='pro_shopName',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
