# Generated by Django 3.2.3 on 2021-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0009_shopperproduct_pro_shopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperproduct',
            name='pro_ID',
            field=models.CharField(max_length=20),
        ),
    ]
