# Generated by Django 3.2.3 on 2021-07-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0011_alter_shopperproduct_pro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='topProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30)),
                ('pro_shopName', models.CharField(default='none', max_length=30)),
                ('pro_desc', models.TextField(max_length=100)),
                ('pro_price', models.IntegerField()),
                ('pro_img', models.ImageField(upload_to='img/')),
                ('pro_ID', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
