# Generated by Django 3.2.3 on 2021-07-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0012_topproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ev_name', models.CharField(max_length=100)),
                ('Ev_desc', models.CharField(max_length=200)),
                ('Ev_Img', models.ImageField(upload_to='event/')),
                ('Ev_Date', models.DateField()),
            ],
        ),
    ]
